// Generated by gencpp from file id_data_msgs/ID_Data.msg
// DO NOT EDIT!


#ifndef ID_DATA_MSGS_MESSAGE_ID_DATA_H
#define ID_DATA_MSGS_MESSAGE_ID_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace id_data_msgs
{
template <class ContainerAllocator>
struct ID_Data_
{
  typedef ID_Data_<ContainerAllocator> Type;

  ID_Data_()
    : id(0)
    , data()  {
      data.assign(0);
  }
  ID_Data_(const ContainerAllocator& _alloc)
    : id(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef boost::array<int32_t, 8>  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::id_data_msgs::ID_Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::id_data_msgs::ID_Data_<ContainerAllocator> const> ConstPtr;

}; // struct ID_Data_

typedef ::id_data_msgs::ID_Data_<std::allocator<void> > ID_Data;

typedef boost::shared_ptr< ::id_data_msgs::ID_Data > ID_DataPtr;
typedef boost::shared_ptr< ::id_data_msgs::ID_Data const> ID_DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::id_data_msgs::ID_Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::id_data_msgs::ID_Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace id_data_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'id_data_msgs': ['/home/robot/catkin_ws_base/src/id_data_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::id_data_msgs::ID_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::id_data_msgs::ID_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::id_data_msgs::ID_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::id_data_msgs::ID_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::id_data_msgs::ID_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::id_data_msgs::ID_Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::id_data_msgs::ID_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17268f86caecf51769ca5729d0bb14c9";
  }

  static const char* value(const ::id_data_msgs::ID_Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17268f86caecf517ULL;
  static const uint64_t static_value2 = 0x69ca5729d0bb14c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::id_data_msgs::ID_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "id_data_msgs/ID_Data";
  }

  static const char* value(const ::id_data_msgs::ID_Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::id_data_msgs::ID_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32[8] data\n\
";
  }

  static const char* value(const ::id_data_msgs::ID_Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::id_data_msgs::ID_Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ID_Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::id_data_msgs::ID_Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::id_data_msgs::ID_Data_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ID_DATA_MSGS_MESSAGE_ID_DATA_H
